# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "o31n/c5bqp59WUyPkgH1cSwOyInlDuixZWdBq+AaumCOURFLcWGTGHpKwU4p+i1GrOKp1CoF8G20woNgQSD+KWzsOvaZ0+Y5uI+P2cd9KrRDOIGnnuIc8FapgawhxUciIyRulCwynR3zhdKS3K0ZA4eNm50+g/syysFtczs6fSmH43546Gokz/32tn7KkQXEGkWmqeXwo/u30GdKFbWHkQhQ176FL9lA2j8ArAZGl8ekqkOClzXW/2JiHgUIlU+e5IaNCSQx7Q9hCJqktSpImjXUlEPFR0W/iNpqaBBkiom2XIF1gp8iIu6gF8DaDHxILZlQnBCRxBURoI5rFQpLppV4nJ5y6Ie4VIYkYsxnsW7mzK6s8+0aHd8ArTum2Pac+16/76ZcJSVfRav/FyqgVwz4SpNtvpdM51QrmX8eoxy4BCGTfTT+qnl93vo9eCBNnkhPZKE4EHxFyIoxP4qaOS0VLtPxrRIKCljfjLFHZ2Q5VPDVW/mhlo8+XJwh3kmxg3xD9YJfj5gstTZinarcUfkm813wvn1hF7b7cpGSRpb+zIH+AQFRw/Bg0FYFIl8Y4PSo2NXb/+whEabe9KXuim/oNSfMBeQIzdDngrYOlGZ1oea45UybC3Ok6b2tdRuu9IdiIPYfx/Sg7qBYiSMlj2nuuMa4TNwVDEqLfWLt7gs="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup
      conda install conda-build=2.1.4

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
